[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[terminal]
shell = { program = "zsh", args = ["-l", "-c", "tmux"] }

[window]
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[font]
size = 14.0

[font.normal]
family = "Fira Code"
style = "Light"

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.italic]
family = "Fira Code"
style = "Italic"

[[keyboard.bindings]] # cmd+e -> C-a % (split-window -h in tmux)
key = "e"
mods = "Command"
chars = "\u0001%"

[[keyboard.bindings]] # cmd+shift+e -> C-a " (split-window -v in tmux)
key = "e"
mods = "Command|Shift"
chars = "\u0001\""

[[keyboard.bindings]] # cmd+w -> C-a q (kill-pane in tmux)
key = "w"
mods = "Command"
chars = "\u0001q"

[[keyboard.bindings]] # cmd+n -> C-a Right
key = "o"
mods = "Command"
chars = "\u0001\u001b[C"

[[keyboard.bindings]] # cmd+n -> C-a Left
key = "y"
mods = "Command"
chars = "\u0001\u001b[D"

[[keyboard.bindings]] # cmd+n -> C-a Down
key = "n"
mods = "Command"
chars = "\u0001\u001b[B"

[[keyboard.bindings]] # cmd+i -> C-a Up
key = "i"
mods = "Command"
chars = "\u0001\u001b[A"

[[keyboard.bindings]]
key = "o"
mods = "Command|Option"
action = "SelectNextTab"

[[keyboard.bindings]]
key = "y"
mods = "Command|Option"
action = "SelectPreviousTab"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
action = "SelectNextTab"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
action = "SelectPreviousTab"

[[keyboard.bindings]] # cmd+f -> M-s (search-backward in tmux)
key = "f"
mods = "Command"
chars = "\u001bs"

[[keyboard.bindings]] # ctrl+i -> PgUp (up-line-or-beginning-search in zsh)
key = "i"
mods = "Control"
chars = "\u001b[5~"
